language: go

go:
  - 1.2
  - tip

before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo add-apt-repository -y ppa:gnome3-team/gnome3
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - go build -tags gtk_3_6 -v ./...

script:
  - go test -tags gtk_3_6 ./...

sudo: true

addons:
  apt:
    sources:
    - gtk+3.0
    - libgtk-3-dev
